import "./styles/style.scss";
import "./styles/chat.scss";
import "./styles/registration.scss";
import "./styles/modificators.scss";
import "./styles/header.scss";
import "./scripts/app";
import "./scripts/mainPage";
import "./scripts/router";
import "./scripts/localization"
